<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('broker_settings',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete();$t->string('broker_name');$t->string('symbol')->default('XAUUSDm');$t->decimal('contract_size',16,4);$t->decimal('min_lot',12,4);$t->decimal('max_lot',12,4);$t->decimal('lot_step',12,4);$t->decimal('tick_size',16,8);$t->decimal('tick_value',16,4);$t->unsignedTinyInteger('digits');$t->decimal('spread',12,4)->nullable();$t->timestamps();});
 Schema::create('candles',function(Blueprint $t){$t->id();$t->string('symbol',30)->index();$t->string('timeframe',5)->index();$t->timestampTz('opened_at')->index();foreach(['open','high','low','close'] as $c)$t->decimal($c,18,6);$t->decimal('volume',20,4)->default(0);$t->unique(['symbol','timeframe','opened_at']);});
 Schema::create('signals',function(Blueprint $t){$t->id();$t->string('symbol',30);$t->string('timeframe',5);$t->string('signal',20);$t->decimal('entry_low',18,6)->nullable();$t->decimal('entry_high',18,6)->nullable();$t->decimal('stop_loss',18,6)->nullable();$t->jsonb('take_profits')->nullable();$t->unsignedTinyInteger('confidence');$t->string('status',20)->default('pending');$t->jsonb('analysis');$t->timestampsTz();});
 Schema::create('economic_events',function(Blueprint $t){$t->id();$t->string('provider_id')->unique();$t->string('currency',5);$t->string('event');$t->string('impact',10);$t->timestampTz('scheduled_at')->index();$t->string('previous')->nullable();$t->string('forecast')->nullable();$t->string('actual')->nullable();$t->timestamps();});
 Schema::create('trade_journals',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->dateTimeTz('traded_at');$t->string('direction',4);$t->decimal('entry',18,6);$t->decimal('exit',18,6)->nullable();$t->decimal('stop_loss',18,6)->nullable();$t->decimal('take_profit',18,6)->nullable();$t->decimal('lot',12,4);$t->decimal('profit_loss',16,2)->nullable();$t->string('screenshot_path')->nullable();$t->text('reason')->nullable();$t->text('notes')->nullable();$t->string('emotion')->nullable();$t->string('strategy')->nullable();$t->timestampsTz();});
 }public function down():void{Schema::dropIfExists('trade_journals');Schema::dropIfExists('economic_events');Schema::dropIfExists('signals');Schema::dropIfExists('candles');Schema::dropIfExists('broker_settings');}};
